from main import part_1, part_2

TEST_INPUT = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


def test_part_1():
    assert part_1(TEST_INPUT) == 14


def test_part_2():
    answer = part_2(TEST_INPUT)
    assert answer == 34


if __name__ == '__main__':
    test_part_1()
    test_part_2()
